baseURL: 
languageCode: en-us
title: Dressing up Data
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Grace Acton
enableEmoji: yes
publishDir: docs
params:
  author: 
    description: 
    name: Grace Acton
    thumbnail: /images/batespic.jpeg
  description: 
  index:
    alertbar: no
    mdtext: |
      I'm Grace, a textile history enthusiast and Digital Archives student.  
      This site is a compendium of my data analysis and visualization work, historic dress research, and sewing endeavors.  
      
      #### Navigating this Site
      **Blog**: This is where I'll post updates on current projects and research.   
      **Seamstresses Project**: My first complete, independent digital history project. 
                                View interactive maps and a presentation about 
                                seamstresses in early 19th-century New England.
      
  
    picture: /images/osv_maintenance.jpeg
    subtitle: Welcome to Dressing Up Data!
    title: Hello!
  logo: 
  social:
    github: gkacton
    instagram: dressing-up-data
    linkedin: gkacton
menu:
  main:
    - identifier: about
      name: About Me
      url: /static/about
      weight: 200
    - identifier: seamstresses
      name: Seamstresses Project
      url: /static/seamstresses-about
      weight: 200
    - identifier: blog
      name: Blog
      url: /blog
      weight: 100

