baseURL: https://example.com/
languageCode: en-us
title: Mediumish
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Grace Acton
enableEmoji: yes
publishDir: docs
params:
  author: 
    description: 
    name: Grace Acton
    thumbnail: /images/batespic.jpeg
  description: 
  index:
    alertbar: no
    mdtext: |
      Currently trying to get this blog running, still don't know what the blog will be about!\
      **This textblock is a demonstration of the mdtext-param.**\
      ### This is a markdown heading
    picture: /images/batespic.jpeg
    subtitle: 
    title: Grace Acton
  logo: 
  social:
    github: gkacton
    instagram: <username>
    linkedin: <username>
menu:
  main:
    - identifier: about
      name: About Me
      url: /
      weight: 200
    - identifier: seamstresses
      name: Seamstresses Project
      url: /static/imprint
      weight: 200
    - identifier: blog
      name: Blog
      url: /blog
      weight: 100

