baseURL: https://example.com/
languageCode: en-us
title: Dressing up Data
theme: mediumish-gohugo-theme
summaryLength: 25
copyright: Grace Acton
enableEmoji: yes
publishDir: docs
params:
  author: 
    description: 
    name: Grace Acton
    thumbnail: /images/batespic.jpeg
  description: 
  index:
    alertbar: no
    mdtext: 
    picture: /images/osv_maintenance.jpeg
    subtitle: 
    title: Welcome!
  logo: 
  social:
    github: gkacton
    instagram: <username>
    linkedin: <username>
menu:
  main:
    - identifier: about
      name: About Me
      url: /static/about
      weight: 200
    - identifier: seamstresses
      name: Seamstresses Project
      url: /static/seamstresses-about
      weight: 200
    - identifier: blog
      name: Blog
      url: /blog
      weight: 100

