---
title: About Me
author: Grace Acton
date: '2022-05-16'
slug: about
categories:
  - about
  - setup
tags: []
publishdate: '2022-05-16T11:32:16-04:00'
comments: yes

---
## Hi, I'm Grace!  
I'm a junior at Bates College in Lewiston, Maine.   
      
### Course of Study  
**Major**: Digital Archives. This interdisciplinary major combines courses
      from Digital and Computational Studies (DCS) and History to explore how we
      can learn more about the lives of people in the past by using the digital 
      tools of the present.  
**Minors**: Mathematics and Russian Language.  
      
### Interests

Data visualization in R  
Digital History  
Textile and Fashion History  
Textile Conservation  
Museums and Public History  

### Current Courses

Advanced Russian
Technology in US History
Upstairs, Downstairs, and Outside: The Household in British History
Museum Internship at the Bates College Museum of Art 

### Current Project at the Bates Museum of Art

I'm currently working on helping the Bates Museum of Art develop a crowdsourcing platform to re-tag the art in our digital collection database. When the collection database was made, there was no consistent schema in place for how to tag artworks. As a result, the database is not easily searchable or filter-able, and there are several works that have no tagging beyond the object type. There are 8,000 works in the collection, making it impossible for the small museum staff to re-tag everything themselves.We are looking to use [Zooniverse](https://www.zooniverse.org/projects) to host a crowdsourcing project, which will let art-loving volunteers provide tags for us! I'm very excited to be working on this project, and will post updates as we move forward!